apiVersion: v1
kind: ConfigMap
metadata:
  name: labdropbox-config
data:
  SERVICE_PORT: "8080"
  SERVICE_NAME: "labdropbox-service"
  CHUNK_SIZE_MB: "1"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_BUCKET_NAME: "labdropbox"
  MINIO_USE_SSL: "false"
  TIDB_HOST: "tidb"
  TIDB_PORT: "4000"
  TIDB_USER: "root"
  TIDB_DATABASE: "labdropbox"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  JAEGER_ENDPOINT: "jaeger:4318"
---
apiVersion: v1
kind: Secret
metadata:
  name: labdropbox-secret
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  TIDB_PASSWORD: ""
  REDIS_PASSWORD: ""
